language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - npm --version
  - node --version
  - npm i -g @angular-cli
  - ng version
install:
  - npm i
before_script:
  - ng build
script:
  - ls -al
#  - npm run single-test
#  - ng e2e
#  - npm t --browsers=ChromeHeadlessNoSandbox
